// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsdHStG5RfdgLdR3ahzh3v5HYB6Qi0mLk',
    appId: '1:571235877710:web:4052fbd1f6cf51fd7cd41f',
    messagingSenderId: '571235877710',
    projectId: 'movie-bd1c7',
    authDomain: 'movie-bd1c7.firebaseapp.com',
    storageBucket: 'movie-bd1c7.appspot.com',
    measurementId: 'G-QFGRMYSF7S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0JgodOYFTLMZ7yFPp4hIEmT8KJ1Sx9d0',
    appId: '1:571235877710:android:e0056957b30da4a17cd41f',
    messagingSenderId: '571235877710',
    projectId: 'movie-bd1c7',
    storageBucket: 'movie-bd1c7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD73l_rZK2V1qrBPgy-uMQJR5BIg_pxw4c',
    appId: '1:571235877710:ios:6ba1126e076914ca7cd41f',
    messagingSenderId: '571235877710',
    projectId: 'movie-bd1c7',
    storageBucket: 'movie-bd1c7.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD73l_rZK2V1qrBPgy-uMQJR5BIg_pxw4c',
    appId: '1:571235877710:ios:6ba1126e076914ca7cd41f',
    messagingSenderId: '571235877710',
    projectId: 'movie-bd1c7',
    storageBucket: 'movie-bd1c7.appspot.com',
    iosBundleId: 'com.example.movieApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsdHStG5RfdgLdR3ahzh3v5HYB6Qi0mLk',
    appId: '1:571235877710:web:cec998e06de6e7187cd41f',
    messagingSenderId: '571235877710',
    projectId: 'movie-bd1c7',
    authDomain: 'movie-bd1c7.firebaseapp.com',
    storageBucket: 'movie-bd1c7.appspot.com',
    measurementId: 'G-1RF12D023K',
  );
}
